spring.application.name=online
#configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.indent_output=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
logging.level.org.springframework.security=DEBUG
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.access-minutes=60
app.jwt.refresh-days=14
server.servlet.session.timeout=0

